# -- cooding: utf-8 --
x=input()
print('i:', x[2])
print('')
print('ii:', x[-2])
print('')
print('iii:', x[:5])
print('')
print('iv:', x[:-2])
print('')
print('v:', x[::2])
print('')
print('vi:', x[1::2])
print('')
print('vii:', x[::-1])
print('')
print('viii:', x[::-2])
print('')
print('ix', len(x))
print('')
